x = input("Введите текст ")
x = x.replace("а", "")
x = x.replace("у", "")
x = x.replace("е", "")
x = x.replace("ы", "")
x = x.replace("о", "")
x = x.replace("э", "")
x = x.replace("я", "")
x = x.replace("и", "")
x = x.replace("ю", "")
print(x)
